server:
  port: 8761 

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false  

  server:
    enableSelfPreservation: false  # Disable self-preservation for demo purposes (useful during development)
